# Generated by Django 5.1.4 on 2024-12-20 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_alter_employee_course_alter_employee_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 12, 0)),
        ),
    ]
